### ISSUE TITLE
All keywords should probably be replaced at the same time

### ISSUE THREAD

**Issue by Debilski** [ASPP/massmail#17]
Replacing the keywords one after another requires either additional escaping of $ or should be done at the same time for all keywords.

**Comment by pberkes** [comment]
For example, for parameters
```
$EMAIL$;$NAME$;$VALUE$
testrecv@test.org;$VALUE$;$NAME$
```

and email body
`$VALUE$ $NAME$`

we would expect as result `$NAME$ $VALUE$`, but we do not: it's either `$NAME$ $NAME$` or `$VALUE$ $VALUE$`, depending on the order of the dictionary used in the implementation.

**Comment by pberkes** [comment]
(don't fix this for the moment I might use it in my class)

**Comment by jakobj** [comment]
this should do the trick:
```python
lbody = re.sub('\$[A-z]+\$', lambda m: keywords[m.group(0)][i], body)
```
